name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build OpenAPI source code
        run: docker run --rm -v "$(pwd):/local" openapitools/openapi-generator-cli generate -i /local/openapi/openapi.yaml -g elm -o /local/openapi/dest

      - name: Build
        run: npm run build -- //mikoto2000.github.io/bookmarks/

      - name: ls
        run: ls && ls ./dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

